/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reminder;

/**
 *
 * @author Prasad-pc
 */
import java.io.*;
import java.lang.*;
import java.time.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.*;
import java.time.format.*;
import java.time.format.*;
import java.time.chrono.*;
import java.util.*;
import java.nio.file.*;
import java.nio.channels.*;
import java.nio.*;
import supportive.Resources;    //  User-defined package
import circularlinkedlist.*;
//	import javafx.application.Platform;
import java.net.URL;
import javax.sound.sampled.*;
import reminder.*;
import scheduler.*;
import personalassistant.*;
import java.awt.event.*;
import java.awt.*;
import javax.swing.*;

public class SwingSound extends javax.swing.JFrame {
	Clip clip;
	/**
	 * Creates new form SwingSound
	 */
	public SwingSound() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlelbl = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cmtarea = new javax.swing.JTextArea();
        cmtlbl = new javax.swing.JLabel();
        okbtn = new javax.swing.JButton();
        namelbl = new javax.swing.JLabel();
        tdlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alarm");
        setAlwaysOnTop(true);

        titlelbl.setText("Name:");

        timelbl.setText("Time:");

        cmtarea.setEditable(false);
        cmtarea.setBackground(new java.awt.Color(204, 204, 255));
        cmtarea.setColumns(20);
        cmtarea.setRows(5);
        cmtarea.setToolTipText("Your Brief Comments");
        jScrollPane1.setViewportView(cmtarea);

        cmtlbl.setText("Brief info:");

        okbtn.setText("Ok");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });

        namelbl.setText("jLabel1");

        tdlbl.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cmtlbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(okbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titlelbl)
                            .addComponent(timelbl))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tdlbl)
                            .addComponent(namelbl))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timelbl)
                    .addComponent(tdlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmtlbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okbtn))
        );

        titlelbl.getAccessibleContext().setAccessibleName("titlelbl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okbtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SwingSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SwingSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SwingSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SwingSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SwingSound().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cmtarea;
    private javax.swing.JLabel cmtlbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namelbl;
    private javax.swing.JButton okbtn;
    private javax.swing.JLabel tdlbl;
    private javax.swing.JLabel timelbl;
    private javax.swing.JLabel titlelbl;
    // End of variables declaration//GEN-END:variables
	
	public void playSound(InputReminder ir){
		namelbl.setText(ir.title);
		tdlbl.setText(ir.adate + ", " + ir.ahour+":"+ir.amin+":"+ir.asec);
		cmtarea.setText(ir.cmt); cmtarea.setWrapStyleWord(true);
		AudioInputStream ais;
		String path = Resources.DIR + "sherlock.wav";
		try{
			ais = AudioSystem.getAudioInputStream(new File(path).getAbsoluteFile());
			clip = AudioSystem.getClip();
			
			//	Open audioInputStream
			clip.open(ais);
			
			clip.loop(Clip.LOOP_CONTINUOUSLY);
			clip.start();
			//	Resources.getch();
			//	clip.stop();
			//	clip.close();
			okbtn.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent ae){
				//	System.exit();
				clip.stop(); clip.close();
				dispose();
				//	System.exit(0);
				//	return; 
			}
		});
			
		}catch(Exception e){
			Resources.show("line 70");
			Resources.showerr(e);
		}
		//	Application.launch("Why");
	}

}
